version: '2.2'

services:

  oce-broker-0:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=0

    cpu_count: 4
    mem_limit: 4G
    mem_reservation: 1G

  oce-broker-1:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=1

    cpu_count: 4
    mem_limit: 4G
    mem_reservation: 1G

  oce-broker-2:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod,dispatcher,delivery

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=2

    cpu_count: 4
    mem_limit: 4G
    mem_reservation: 1G

  oce-me:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod,matcher

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=3

    cpu_count: 4
    mem_limit: 4G
    mem_reservation: 1G

  oce-nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - ./oce-nginx/conf.d:/etc/nginx/conf.d/
      - ./oce-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8081:3000"
    depends_on:
      - oce-broker-0
      - oce-broker-1
      - oce-broker-2
      - oce-me
    cpu_count: 4
