version: '2.2'

services:

  oce-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  oce-kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST_MACHINE_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: oce-zookeeper:2181
    depends_on:
      - oce-zookeeper

  oce-mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    mem_limit: 512M
    mem_reservation: 256M

  oce-mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=201904-exchange

  oce-redis:
    image: redis:4

  oce-0:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod,dispatcher,delivery,matcher

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=0
    depends_on:
      - oce-kafka
      - oce-mysql
      - oce-mongo
    mem_limit: 1G
    mem_reservation: 512M

  oce-nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - ./oce-nginx/conf.d:/etc/nginx/conf.d/
      - ./oce-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:3000"
    depends_on:
      - oce-0
