
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/201904-exchange?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 200
      max-lifetime: 1800000
      minimum-idle: 5
      validation-timeout: 3000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /

snowflake:
  dataCenterId: 0
  machineId: 0

table:
  shared:
    order4user: 10 # 用户订单表分片 10 个

#logging:
#  level:
#    io: debug
