{
 "title": "cost time",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "oce place cost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "placeOrder" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "placeOrder" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cost" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "placeOrder" }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "asset change cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cancel-max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderCancel" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "cancel-min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderCancel" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cancel-mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderCancel" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "deal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderDeal" }
     ]
    }
   ]
  },
  {
   "title": "order change cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "place" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-place" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "deal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-deal" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cancel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-cancel" }
     ]
    }
   ]
  },
  {
   "title": "counter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "query-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "queryOrderList" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "place-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "placeOrder" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "order-change-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-place" },
      { "condition": "OR", "key": "task", "operator": "=", "value": "order-deal" },
      { "condition": "OR", "key": "task", "operator": "=", "value": "order-cancel" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "asset-change-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderCancel" },
      { "condition": "OR", "key": "task", "operator": "=", "value": "asset-orderDeal" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "level1-count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level1" },
      { "condition": "OR", "key": "task", "operator": "=", "value": "level2" }
     ]
    }
   ]
  },
  {
   "title": "level1&2 cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "level1.max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "level1.mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "level2.mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level2" }
     ]
    }
   ]
  },
  {
   "title": "query order cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "queryOrderList" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "queryOrderList" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "queryOrderList" }
     ]
    }
   ]
  },
  {
   "title": "asset change retry-count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "retryCounter",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "retryCount" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "retryCounter",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "retryCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}