{
 "title": "cost time",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "oce place max cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "symbol" ], "type": "tag" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cost" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "placeOrder" }
     ]
    }
   ]
  },
  {
   "title": "asset max cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cancel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderCancel" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "deal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "asset-orderDeal" }
     ]
    }
   ]
  },
  {
   "title": "order max cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "query": "SELECT \"total\" FROM \"place_order_elapsed\" WHERE (\"symbol\" = 'btc-usdt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "place" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-place" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "deal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-deal" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "cancel" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "order-cancel" }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "level1 cost",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "level1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elapsed",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "level2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "task", "operator": "=", "value": "level2" }
     ]
    }
   ]
  }
 ]
}