version: '2.2'

services:

  oce-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  oce-kafka:
    image: wurstmeister/kafka:latest
    volumes:
      - ${KAFKA_VOLUMES}:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST_MACHINE_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: oce-zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - oce-zookeeper

  oce-mongo:
    image: mongo:4
    volumes:
      - ${MONGODB_VOLUMES}:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    mem_limit: ${MONGODB_MEM_LIMIT}

  oce-mysql:
    image: mysql:5.6
    command: --innodb-log-buffer-size=${MYSQL_INNODB_LOG_BUFFER_SIZE}
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=201904-exchange
    ports:
      - "3306:3306"

  oce-redis:
    image: redis:4
    command: redis-server --appendonly yes --aof-use-rdb-preamble yes
    volumes:
      - ${REDIS_VOLUMES}:/data

  oce-broker-0:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=0
    mem_limit: ${OCE_MEM_LIMIT}
    depends_on:
      - oce-kafka
      - oce-mysql
      - oce-mongo

  oce-broker-1:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod,dispatcher,delivery

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=1
    mem_limit: ${OCE_MEM_LIMIT}
    depends_on:
      - oce-kafka
      - oce-mysql
      - oce-mongo

  oce-me:
    image: qyvlik/oce:latest
    volumes:
      - ./oce/application.yml:/home/www/application.yml:ro
      - ./oce/application-prod.yml:/home/www/application-prod.yml:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod,matcher

      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

      - SPRING_REDIS_DATABASE=${REDIS_DATABASE}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - SPRING_DATA_MONGODB_URI=${MONGO_URI}

      - SNOWFLAKE_DATACENTERID=0
      - SNOWFLAKE_MACHINEID=4
    mem_limit: ${OCE_MEM_LIMIT}
    depends_on:
      - oce-kafka
      - oce-mysql
      - oce-mongo

  oce-nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - ./oce-nginx/conf.d:/etc/nginx/conf.d/
      - ./oce-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:3000"
    depends_on:
      - oce-broker-0
      - oce-broker-1
      - oce-me
